### ISSUE TITLE
Can't tell that MISP messages are making it to backbone

### ISSUE THREAD

**Issue by mdavis332** [tenzir/threatbus#27]
### Observed Behavior
Guten Tag!
Running tenzir/threatbus:latest docker container and mounting config.yaml as volume. I believe it's successfully talking to my MISP instance, but there's no indication the backbone is getting traffic (debug for console turned on but nothing showing up in STDOUT on `docker-compose logs -f`). As an aside, I'm not using the zeek portion of the config at all (no Zeek instance). 

Ultimately, I'm looking at writing a threatbus plugin to take the MISP messages that are published to in_mem and submit those as indicators to another threat intel platform (CIF) using [that python client](https://github.com/csirtgadgets/cifsdk-py-v3). 

### Expected Behavior
I've got an alpha CIF plugin for threatbus written, but it doesn't appear to be getting any data, which makes me think the publisher for MISP perhaps isn't publishing like I would expect? I've been adding logger.debug statements everywhere to hopefully find where something isn't going right, but so far no luck.

### Steps to reproduce

1. docker-compose up -d
2. docker-compose logs -f
3. See just startup info

```
Attaching to threatbus
threatbus    | 2020-05-22 20:23:04 INFO     [threatbus] Starting plugins...
threatbus    | 2020-05-22 20:23:04 INFO     [threatbus_zeek.plugin] Broker: endpoint listening - localhost:47761
threatbus    | 2020-05-22 20:23:04 INFO     [threatbus_zeek.plugin] Zeek plugin started
threatbus    | WARNING [api.py:82 - __init__() ] The version of PyMISP recommended by the MISP instance (2.4.126) is newer than the one you're using now (2.4.125). Please upgrade PyMISP.
threatbus    | 2020-05-22 20:23:04 INFO     [threatbus_misp.plugin] MISP plugin started
threatbus    | 2020-05-22 20:23:04 INFO     [threatbus_inmem.plugin] In-memory backbone started.
```

### Environment Context

- Version: latest docker image
- Compiler:
- Operating System: host is Ubuntu 1804

### Config.yaml

```
logging:
  console: true
  console_verbosity: DEBUG
  file: false
  file_verbosity: DEBUG
  filename: threatbus.log

plugins:
  apps:
    zeek:
      host: localhost
      port: 47761
      module_namespace: Tenzir
    misp:
      api:
        host: https://192.168.0.2:8006
        ssl: false
        key: <MISP_API_KEY>
      zmq:
        host: 192.168.0.2
        port: 50000
```

### docker-compose.yml

```
version: '3.0'
services:
  threatbus:
    image: tenzir/threatbus:latest
    container_name: threatbus
    hostname: threatbus
    volumes:
      - ./config.yaml:/opt/tenzir/threatbus/config.yaml
    command: -c config.yaml
```

vielen Dank!
